"use client";

import { motion } from "framer-motion";
import Image from "next/image";
import { EMAIL_ADDRESS } from "../lib/constants";
import { fadeInButton, textFadeUp, textFadeUpSmall } from "../lib/motion";
import projectStyles from "./Project.module.css";

interface ProjectProps {
  title: string;
  html: string;
  images?: string[];
}

export function Project({ title, html, images = [] }: ProjectProps) {
  return (
    <>
      <motion.h1
        className="title"
        variants={textFadeUp(0, 0.45)}
        initial="hidden"
        whileInView="show"
        viewport={{ once: true, amount: 0.15 }}
      >
        {title}
      </motion.h1>

      <div className={projectStyles.wrapper}>
        <article>
          {html ? (
            <div>
              <motion.div
                variants={textFadeUpSmall(0.08, 0.4)}
                initial="hidden"
                animate="show"
                className={projectStyles.content}
                // Safe: html is generated by `marked` from static markdown files in
                // /content/projects that only the repo owner can modify. No user
                // input reaches this render path.
                dangerouslySetInnerHTML={{ __html: html }}
              />
            </div>
          ) : null}
        </article>
      </div>

      {images.length > 0 && (
        <div className={projectStyles.masonryGrid}>
          {images.map((src, i) => (
            <div key={i} className={projectStyles.masonryItem}>
              <Image
                src={src}
                alt={`${title} — project image ${i + 1}`}
                width={0}
                height={0}
                sizes="(max-width: 699px) 100vw, 50vw"
                style={{ width: "100%", height: "auto", display: "block" }}
              />
            </div>
          ))}
        </div>
      )}

      {html && (
        <motion.div
          className={projectStyles.emailInfo}
          variants={fadeInButton("up", 0.18, 0.35)}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, amount: 0.15 }}
        >
          Interested in working together?
          <br />
          Feel free to email us at{" "}
          <a
            className={projectStyles.emailLink}
            href={`mailto:${EMAIL_ADDRESS}`}
          >
            {EMAIL_ADDRESS}
          </a>
        </motion.div>
      )}
    </>
  );
}
